### ISSUE TITLE
Environement build fix, and add REQUEST_METHOD

### ISSUE THREAD

**Issue by manu0401** [phokz/mod-auth-external#24]
The attached patch fixes the build on recent apache 2.4 (remote_ip was split within client_ip and useragent ip). It also adds REQUEST_METHOD to the environment.
[patch-aa.txt](https://github.com/phokz/mod-auth-external/files/206071/patch-aa.txt)

**Comment by bimimicah** [comment]
This is a duplicate of #8, which has already been fixed, and #19, a feature request.
Thank you for your contribution.
