### ISSUE TITLE
Tag version 3.3.2

### ISSUE THREAD

**Issue by candrews** [phokz/mod-auth-external#35]
Can you please tag version 3.3.2 (I believe that's commit 0ee39e) and consider making a new release which would be 3.3.3 (as there have a been a few commits since the last release that would be nice to have)?

Thanks!

(BTW, I'm the Gentoo maintainer of this package)

**Comment by joakim-tjernlund** [comment]
Can you package mod_authnz_unixgroup as well ?

**Comment by bimimicah** [comment]
Version 3.3.2 of mod_authnz_external has been tagged, and versions 1.0.3 and 1.1.0 of mod_authz_unixgroup have now been tagged.

I will talk to @phokz about the possibility of CI builds (e.g. Travis-CI which is free for open source) before I try to make a new release.

**Comment by bimimicah** [comment]
We now have CI builds on linux, mac, and windows.

**Comment by bimimicah** [comment]
Version 3.3.3 has been released.
