### ISSUE TITLE
mod_authnz_external.c:496]: (style) Suspicious condition

### ISSUE THREAD

**Issue by dcb314** [phokz/mod-auth-external#36]
mod_authnz_external.c:496]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.

Source code is

       ((rc= apr_procattr_child_errfn_set(procattr, extchilderr)
              != APR_SUCCESS)))

Maybe better code

       ((rc= apr_procattr_child_errfn_set(procattr, extchilderr))
              != APR_SUCCESS))

**Comment by bimimicah** [comment]
Included in release v3.3.3
