### ISSUE TITLE
How do I use mod_authnz_external with php on Windows?

### ISSUE THREAD

**Issue by bloodtearvn** [phokz/mod-auth-external#41]
I try to config each folder for each user (or folder can access (or not)  by mutl user)
I got log from apache log
[Mon Mar 30 15:10:49.181579 2020] [authnz_external:error] [pid 9352:tid 1904] [client xxx.xxx.xx.xxx:53116] AuthExtern auth "folder" Failed (-1) for user test1

My config:
DefineExternalAuth auth environment D:/xampp/htdocs/private/auth.php
<Directory D:/xampp/htdocs/myfoldersecret>
        Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
	AuthBasicProvider external
        AuthType Basic
        AuthName "Restricted area"                
        Require valid-user
	AuthExternal auth		
    </Directory>

My code for check valid user php
> $realm = 'Restricted area';
> $validUser = getenv('USER');
> $validPass = getenv("PASS");
> $db_host="localhost"; //localhost server 
> $db_user="root"; //database username
> $db_password=""; //database password   
> $db_name="db_tmp"; //database name
> $uri = $_SERVER['REQUEST_URI'];
> $uri=explode("/",$uri);
> if (empty($uri[count($uri)]))
>   $folder_name=$uri[count($uri)-2];
> else
>   $folder_name=$uri[count($uri)-1];
> try
> {
>  $db=new PDO("mysql:host={$db_host};dbname={$db_name}",$db_user,$db_password);
>  $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
> }
> catch(PDOEXCEPTION $e)
> {
>   exit(1);
> }  
> $select_stmt=$db->prepare("SELECT * FROM tbl_user WHERE user_login=:uname AND folder_name=:folder_name"); 
> $select_stmt->execute(array(':uname'=>$validUser,':folder_name'=>$folder_name)); 
> $row=$select_stmt->fetch(PDO::FETCH_ASSOC);
> if ($select_stmt->rowCount() > 0)
> {    
>     $cryptor = new Cryptor($encryption_key);
>     $token= $cryptor->decrypt($row['user_password']);    
>     if ($validPass!=$token)    
>       requireLogin($realm,$nonce);      
>     else
>       exit(0);
> }
> else
>   requireLogin($realm,$nonce);
> 
> // This function forces a login prompt
> function requireLogin($realm,$nonce) {
>     header('WWW-Authenticate: Basic realm="' . $realm . '"');
>     header('HTTP/1.0 401 Unauthorized');
>     echo 'Text to send if user hits Cancel button';
>     exit;  
> }

**Comment by bimimicah** [comment]
It looks like you are using a Windows environment. On Windows you cannot directly execute PHP files as programs. You have to execute php.exe and pass the PHP script file as a parameter.
For example:

> DefineExternalAuth auth environment "_C:\wamp64\bin\php\php5.6.31\php.exe_ -f D:/xampp/htdocs/private/auth.php"

Replace _C:\wamp64\bin\php\php5.6.31\php.exe_ with the path to your php executable on your system and then try again.

**Comment by bloodtearvn** [comment]
I got error password missmath now. 
> <?php
> $username = $PHP_AUTH_USER;
> $password = $PHP_AUTH_PW;
> if ($username=="admin" && $password=="123")
> exit(0);
> else
> exit(1);
> ?>

**Comment by bloodtearvn** [comment]
> <?php
> $username = $PHP_AUTH_USER;
> $password = $PHP_AUTH_PW;
> if ($username=="admin" && $password=="123")
> exit(0);
> else
> exit(1);
> ?>

**Comment by bimimicah** [comment]
In your last example, replace:

> $username = $PHP_AUTH_USER;
$password = $PHP_AUTH_PW;

with:

> $username = getenv("USER");
$password = getenv("PASS");

**Comment by bloodtearvn** [comment]
i change it and this is run OK, now i try to make full code again

**Comment by bloodtearvn** [comment]
how can i log some variables on code php for debug?
eg: i want to show user and pass that they enter and check agian 
when i back to full code i password mismath too

**Comment by bimimicah** [comment]
Try one of these:

> fwrite(STDERR, "<your error/log message here> \n");

> error_log("<your error/log message here>");

**Comment by bloodtearvn** [comment]
Thanks bimimicah i got error: Undefined index: REQUEST_URI how can i folder that user want access in php cli

**Comment by bimimicah** [comment]
Instead of `$_SERVER["REQUEST_URI"]`, you would use:

> getenv("URI")

see [the wiki](https://github.com/phokz/mod-auth-external/wiki/AuthHowTo) for info on the available environment variables

Please note that things that would normally be part of the PHP setup as an apache module (like most $_SERVER variables) **do not exist** in this context, because you are running a PHP script standalone/**external**-ly to handle the authentication. It's just like double-clicking on PHP.exe and typing in your PHP script file line by line, plus whatever information mod_auth_external specifically adds (such as the environment variables listed in the wiki above)

**Comment by bimimicah** [comment]
If there are no more questions, I will go ahead and close this issue sometime soon.
