### ISSUE TITLE
external authenticator PHP instances can't transmit cookies to the browser

### ISSUE THREAD

**Issue by galaxiesFarApart** [phokz/mod-auth-external#42]
Using a PHP script with mod_authnz_external which initiates a PHP session does properly create the session file, present the $_SESSION global array, and is able to populate that session file. However, the expected cookie for that PHP session does not appear to get delivered to the connected browser (FireFox, Opera). When a subsequent web page initiates PHP session, its status shows no current session in progress and it creates a new, empty, session file and establishes the corresponding browser cookie for that new PHP session. Even attempting to use the PHP setcookie function has no noticeable affect.

mod_authnz_external usage setup in ssl.conf:
   SetEnv INDICATOR_VAR "{Home}"
   LogLevel authnz_external:trace8
   AllowOverride None
   Options None
   SSLRequireSSL
   <RequireALL>
   Require ip x.x.x.0/24 127.0.0.1
   AuthType Basic
   AuthName "Homepage"
   AuthBasicProvider socache external
   AuthExternal extAuthUser
   AuthExternalContext "Authorization:Homepage"
   AuthExternalProvideCache On
   AuthnCacheTimeout 120
   AuthnCacheProvideFor external
   Require valid-user
   </RequireALL>

**Comment by bimimicah** [comment]
This is by design.
As I understand it, there are two reasons for this:

1. this module deals solely with Authentication/Authorization, and is not involved at all in actually constructing the requested page: in other words, **this module returns a pass/fail code to apache, and does not output headers or body content**.

1. the PHP script you are running via this module is _external_, meaning it is running in a separate process and is not in the current apache process at all. This means, for example, that PHP execution (via this module) is based solely on factors such as the global php.ini file, and is not at all affected by mod_php directives in apache's config files.

@phokz maybe you would like to weigh in on this?

**Comment by bimimicah** [comment]
In case it is unclear:

browser request comes in to Apache, then Apache does 2 separate things (among many others):
1. **Check Authorization** ->mod_authnz_external -> (e.g.) myPHPAuthChecker.php (separate PHP process returns ok/fail code)

    1. Any **existing cookies _sent by the browser_** can be _**read**_. _Creating_ cookies here is meaningless, since these are external and have nothing to do with Apache/BrowserRequest at all

1. **Actually Build the Page** -> requested file (e.g.) myPHPContent.php -> Apache's registered handler for PHP files (e.g. mod_php)

    1. This is where cookies (including PHPSESSID cookie) are **_created_**

Please note: while you can read the value of an _existing_ PHPSESSID _cookie_ from an external script, the actual $_SESSION data will not be available from the external script unless PHP's global `session.save_path` variable and Apache's mod_php `session.save_path` variable point to the same location. This would depend on your server setup/environment.

**Comment by galaxiesFarApart** [comment]
I realized that both of the mentioned possibilities were, indeed, possible and probable. It was somewhat irritating to find that the PHP session_start function was able to create the expected PHP session file, and using the $_SESSION array - it was possible to populate that file.

I understand the premise of the module's purpose.

I have been trying to find a way around this issue but so far can't see any viable solution (for me). I need both functionalities within the same Apache session/transaction. One other test was to use Apache sessions: session file gets created, expected cookie gets delivered, but session file is empty.

I also noticed that there is no ability to use any PHP apache functions within the module invoked PHP script - again most likely to do the disassociation between my script, the external module, and the active Apache session/transaction.

I don't suppose that there is a way to pass "environment variables" directly back to Apache from mod-auth-external, is there? Unfornately one's "environment variables" aren't always someone else's "environment variables".

**Comment by galaxiesFarApart** [comment]
In other words, if mod-auth-external had the mechanism to somehow attach to Apache's "environment variables" pool, then it might be possible to pass data BACK to Apache that it could then make use of.

**Comment by galaxiesFarApart** [comment]
BTW - my use of mod-auth-external occurs at the Apache directory ACL level, not at the web page presentation level.

**Comment by galaxiesFarApart** [comment]
Right - I encountered the different, initial, locations of PHP and Apache sesssion files and corrected that by inserting a "session_save_path" before any "session_start" invocation. That removed the Apache files and retained only the PHP files.

**Comment by galaxiesFarApart** [comment]
If the possibility of modifying mod-auth-extenral to be able to pass data back to Apache other than a return code is a "no go", then you may close out this conversation. Thanks.

**Comment by bimimicah** [comment]
> 
> 
> Right - I encountered the different, initial, locations of PHP and Apache sesssion files and corrected that by inserting a "session_save_path" before any "session_start" invocation. That removed the Apache files and retained only the PHP files.

Your easiest option is to go down this path, I think.
If you can create the PHPSESSID cookie before running the authorization php script (e.g. by having an unauthenticated landing page that just calls session_start() and redirects), then you can manipulate that existing session in both the external script and the main php file. This does get complicated if you are creating/destroying sessions frequently.

__

The other option you have is to compile your own custom version of mod_authnz_external.
A good starting point would be:

1. [The exec_external() function, note the use of r->headers_in on line 494](https://github.com/phokz/mod-auth-external/blob/44da0e99a244b6c0c230a41b080d0de50a72276c/mod_authnz_external/mod_authnz_external.c#L424)

1. [Apache documentation for r->headers_out](https://ci.apache.org/projects/httpd/trunk/doxygen/structrequest__rec.html#afecc56ea8fb015aa52477dba471a6612)

You would need to figure out a way to get the new header data from the external script into mod_authnz_external too. Maybe a special pipe for this.

**Comment by bimimicah** [comment]
> Your easiest option is to go down this path, I think.
> If you can create the PHPSESSID cookie before running the authorization php script....

Example setup:
before_auth.php -> turn off basic auth
auth_script.php -> turn off all web access (this is internal)
homepage.php/others -> turn on basic auth with mod_authnz_external, using auth_script.php

before_auth.php:
> session_start();
> header("Location: homepage.php");

auth_script.php:
> $pairs = explode(";", getenv("COOKIE"));
> if(!isset($pairs["PHPSESSID"])) exit(5);  //return an error code for session-less requests
> session_name($pairs["PHPSESSID"]);
> session_start();
> change the $_SESSION however you want....

In your apache config, set up a check for the PHPSESSID cookie, if it doesn't exist, redirect to before_auth.php

Is that helpful?

**Comment by galaxiesFarApart** [comment]
Thank you for your thoughts. I have the mod-auth-external source code and have looked at it several times. I also tried to look at some of Apache's API documentation but find it lacking a lot in details.

I have several other options that are less extensive that what I was trying for. It was just so convenient to ask for more from mod-auth-external when it already had the access to the requisite data that the existing Apache mod-auth-dbd, et al, can't provide (part of this is due to data being encrypted and/or hashed).

I will look at your suggestions, possible source code modifications, and other things and see what works out the best. I don't want to turn mod-auth-external into something that it was not intended for, but if I could get a "hook" into Apache's environment variables to pass data back, that might prove useful. Then again, this may wind up being nothing more than "a pipe dream".

**Comment by bimimicah** [comment]
It is an interesting idea, but I am currently the only active contributor on this project, and I don't have time to add something along these lines at the moment. I am also concerned about potential, unforeseen security issues that may arise from allowing external scripts to change Apache data structures in such a way. However, I'd be willing to help answer questions (e.g. about Apache coding) if you do try going down the source code modification route.

**On the other hand**, please note that **my last comment and the first half of the comment before that described a suggestion that does not involve modifying mod_authnz_external in any way**, and should be relatively easy to set up in many cases. (create the PHPSESSID cookie before running the authorization php script)

**Comment by galaxiesFarApart** [comment]
I did a simple add to the authnz_external module to try to retrieve additional variables from Apache, but did not get any data. Wrong Apache directive, wrong directive placement, or desired data not available at the time the setenv directive was executed? OH well. I have resorted back to the original authnz_external code.

It is too bad that there isn't an Apache authZ_socache module to compliment the existing authN_socache module. I have a 5-tier authentication/authorization process in my application so am now in the process of working with memcached for the authorization phase. Authenticaton + socache + authnz_external works just fine.

I have looked a lot at authnz_external and as much of Apache and PHP related internals/configuration/options as I could think of. At this point, I do not plan on making or asking for any further modifications to mod_authnz_external, so you may close out this "conversation". Thanks.

**Comment by galaxiesFarApart** [comment]
P.S. It might not be a bad idea to add a comment to the mod_authnz_external README about the implications of not be able to use PHP sessions from within the authnz_external "authenticator". Maybe that will help to wave off others who might "dream" of attempting the same thing.  ;)

**Comment by 4nanook** [comment]
I will get you the info you requested earlier, just been a bit of a shit
storm recently so haven't had time to get back to it.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
This rather breaks it's usefulness.  The reason I wanted to do so is
that phpadmin is buggy and hackers keep finding ways to make it overwrite
itself, by limiting it to people who authenticate it limit's it's use to my
customers.  These things used to work in older versions.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by bimimicah** [comment]
@4nanook:
Please direct your replies to the thread you created earlier: #43 
I would be happy to help as much as I can.

**Comment by bimimicah** [comment]
@galaxiesFarApart:
I'm sorry we weren't able to find a working option for you. Did you try the option I mentioned [here](https://github.com/phokz/mod-auth-external/issues/42#issuecomment-686612506) and [here](https://github.com/phokz/mod-auth-external/issues/42#issuecomment-686730442) that doesn't require changing mod_authnz_external code?
I may add a note to the wiki about PHP sessions. It does already specifically say "[It is not possible to set cookies from an authentication module.](https://github.com/bimimicah/mod-auth-external/wiki/AuthHowTo#5-other-environment-variables)".

**Comment by galaxiesFarApart** [comment]
I did spend a fair amount of tme looking at "r->headers" and Apache "r->headers_out" but decided that "get the new header data from the external script into mod_authnz_external" was not going to work well for me and it was more than just one datum to store.

The sugestion about "altering basic auth, before it issue session_start, special script to retrieve and modify $_SESSION, and use Apache redirect" was a possilbity, but it was actually more involved than what I had used before and will return to: authenticator script creates and writes multiple datum to local pseudo session file in special directory. The data retrieved is used to complete both the authentication and authorization processes. No more need for Apache Group/authnz validation (which is already part of the DB data retrieved). Further form documents will have access to the special pseudo session file of hashed data and complete their levels of authorization processing using it. No cookies, PHP sessions, or Apache  involved.

I had to remove memcached as something, apparently, between it and Apache was causing CSS/JS file load times to exceed 100-1,000 times their load times without memcached. I looked at browser analytical data and many Internet postings about memcache(d) performance issues. I even had Apache reconfigured to use memcached. Not finding a particular item that could be changed to undo this effect, I decided to not bother with memcached. Yes - I had the latest versions of memcahced and libmemcahced installed. Oh Well.

In the end, I decided, as stated earlier, to leave mod_authnz_external alone and use it only as it already exists. I would NOT be able to do what I need to do in my environment without this module!

I thank you for your thoughtful and meaningful suggestions.

**Comment by galaxiesFarApart** [comment]
I believe that I have discovered what was causing so many process hangups when using memcached along with mod_authnz_external, and this should be noted somewhere in the project documentation (it only took me a month to hit on this!):

For every occurance of a memached instance used within an external script (eg; PHP) invoked by mod_authnz_external, there NEEDS to be a memchaced->quit() call AFTER whatever memcached process is completed, even if it would occur just before the end of the external script. Not doing so may cause many blocked processes which can have a serious affect on the overall external script process.

Before discovering this relationship and not quitting the memcached connection, each mod_authnz_external invocation popped up a new process (I was seeing anywhere from 6 - 8 which were adding anywhere from 2 -8 seconds of script "processing" time). After including the memcached->quit() after EACH code segment making use of memcached, I would either see NO additional/blocked process or only one - and even that would be only for a very brief moment (like a "blip"). I also stopped using persistent memcached connections, but that had no bearing on the blocked processes (with or without persistence).

Using "netstat -cant", I watched the progress of the memcached connections. The number of connections would sometimes rise to 5, but usually stayed at 2-3 during the external script process. Nevertheless, no matter how many memcached connections existed, using the memcached->quit() call appropriately released the script side of the connection and no longer caused child process hangups.

I also used strace to see the externlal script results and they also showed the significant difference between not using the memcached->quit() call and using it everywhere it was needed.

Unfortunately, the PHP documentation and examples, and the plethora of Internet postings about memcached fail to identify the affects of not using memcached->quit() after each connection section.

**Comment by bimimicah** [comment]
> I believe that I have discovered what was causing so many process hangups when using memcached along with mod_authnz_external, and this should be noted somewhere in the project documentation (it only took me a month to hit on this!):
> 
> For every occurance of a memached instance used within an external script (eg; PHP) invoked by mod_authnz_external, there NEEDS to be a memchaced->quit() call AFTER whatever memcached process is completed, even if it would occur just before the end of the external script. Not doing so may cause many blocked processes which can have a serious affect on the overall external script process.

Interesting discovery! Sounds like maybe it would be a good idea to [submit a memcached bug report to php.net](https://bugs.php.net/report.php?package=memcached). I'm not sure if one of [these bugs](https://bugs.php.net/search.php?search_for=&boolean=0&limit=30&order_by=&direction=DESC&cmd=display&status=Open&bug_type=All&project=All&package_name%5B%5D=memcached&php_os=&phpver=&cve_id=&assign=&author_email=&bug_age=0&bug_updated=0&commented_by=) is related to your problem?

Unless I'm misunderstanding you, this issue is in the PHP instances launched by mod_authnz_external, so it is fundamentally an issue in PHP or libmemcached.

**Comment by bimimicah** [comment]
> Before discovering this relationship and not quitting the memcached connection, each mod_authnz_external invocation popped up a new process (I was seeing anywhere from 6 - 8 which were adding anywhere from 2 -8 seconds of script "processing" time). After including the memcached->quit() after EACH code segment making use of memcached, I would either see NO additional/blocked process or only one - and even that would be only for a very brief moment (like a "blip"). I also stopped using persistent memcached connections, but that had no bearing on the blocked processes (with or without persistence).

mod_authnz_external will _always_ launch a new, external process for each file requested by the browser, so the "blip" process is normal.

However, that process is supposed to complete quickly and not block (hence the "blipping"), so if they are blocking, that would seem to be an issue on the PHP side. Hopefully if you file a bug report, it will help them fix the problem for everyone. :)

**Comment by galaxiesFarApart** [comment]
I looked at the two mentioned bug reports. Neither of them, however, really related to what I was seeing. I did look at the bug-reporting archive and didn't see any more related outstanding bugs. I reviewed the bug-reporting page but did not submit it yet.

I am waiting on upgraded H/W to get put into action before going further with reporting anything. I want to test things on something that will be closer to what might be expected of a general server level host. My development hosts are somewhat "small". Adequate for many things, but not so much for truly heavy loads.

**Comment by galaxiesFarApart** [comment]
Danger Will Robinson! Warning! Warning! (Lost In Space)

Hmmm - an interesting, but unwanted, development is that the

mod_authnz_external.x86_64                         3.3.1-7.el7                                    @epel

RPM does NOT supply group name or user name values/variables! And it requires about 20 Perl modules for some reason. BIG TIME FAIL! (not for this version, of course)

**Comment by galaxiesFarApart** [comment]
As a "side note", I just found this document:

https://github.com/memcached/memcached/wiki/Timeouts

I have read it but haven't done a lot about it yet.

**Comment by galaxiesFarApart** [comment]
P.S. I have moved on to much faster, more robust, H/W and I don't even see a "blip" of mod_authnz_external tasks any more, and only one extra memcached connection is established. (sigh!). So I guess that I have already fulfilled some of the above Timeouts tasks/requirements.

**Comment by carrvo** [comment]
Can the major points of this discussion make it into the documentation?

Such as the really helpful Apache example https://github.com/phokz/mod-auth-external/issues/42#issuecomment-686730442 .

**Comment by galaxiesFarApart** [comment]
I stopped trying to use SESSIONS so I have no particular comment about the request to include any part of this discussion into documentation.
