### ISSUE TITLE
Both zip and tarball unpack as mod-auth-external-mod_authnz_external-3.3.3/

### ISSUE THREAD

**Issue by pprindeville** [phokz/mod-auth-external#44]
Not sure why the project name is repeated twice in directory when unpacking (well, once with hyphens and once with underscores)...

**Comment by bimimicah** [comment]
Those source files are auto-generated by GitHub on release. As near as I can tell, they work on the following formula: **\<repository name>-\<release name>.\<extension>**
Due to decisions made back when this project was on Google Code (or maybe earlier), this repository hosts both mod_authnz_external **and** mod_authz_unixgroup. You can see both sets of packages mixed together in the release history.
That's why the files are named as:

- mod-auth-external-mod_authnz_external-3.3.3.zip
- mod-auth-external-mod_authz_unixgroup-1.1.0.zip

So a program like 7zip will typically just use the filename as the unzip folder name.

**Comment by bimimicah** [comment]
And it looks like the same rule applies to the folder inside the zip/tarball

**Comment by bimimicah** [comment]
Did you have further questions or a suggestion for how we could improve this?
If your question has been answered, feel free to close the issue.

**Comment by 4nanook** [comment]
When I try to compile this into httpd-2.4.46 statically, it compiles successfully but the server fails to start with this error:
Apr 29 19:01:30 ftp.eskimo.com apachectl[2210541]: /usr/sbin/httpd: symbol lookup error: /usr/sbin/httpd: undefined symbol: apr_thread_mutex_timedlock

**Comment by 4nanook** [comment]
Ok, the undefined symbol was an issue with apr, fixed that but still when I compile mod-auth-external-mod in php apps do not work, friendica in particular looks like this:
![pw-auth](https://user-images.githubusercontent.com/3466797/116644216-a1e6ac80-a927-11eb-9b69-ba50a0993078.png)
My config file for apache 2.4.46 looks like this:
./configure \
--enable-suexec=static \
--with-suexec-bin=/usr/sbin/suexec \
--with-crypto \
--with-suexec-caller=apache \
--with-suexec-userdir=public_html/cgi-bin/ \
--with-suexec-docroot=/misc/www/ \
--with-suexec-uidmin=2 \
--with-suexec-gidmin=2 \
--without-suexec-logfile \
--with-suexec-syslog \
--with-included-apr \
--bindir=/usr/bin \
--datadir=/usr/share \
--includedir=/usr/include \
--libdir=/usr/lib64 \
--libexecdir=/usr/lib64/httpd/modules \
--mandir=/usr/share/man \
--sbindir=/usr/sbin \
--sysconfdir=/etc/httpd \
--enable-rewrite=static \
--enable-authn-file=static \
--enable-authn-dbm=static \
--enable-authn-anon=static \
--enable-authn-dbd=static \
--enable-authn-socache=static \
--enable-authn-core=static \
--enable-authz-host=static \
--enable-authz-groupfile=static \
--enable-authz-user=static \
--enable-authz-dbm=static \
--enable-authz-owner=static \
--enable-authz-dbd=static \
--enable-authz-core=static \
--enable-access-compat=static \
--enable-auth-basic=static \
--enable-auth-form=static \
--enable-auth-digest=static \
--enable-isapi \
--enable-cache=static \
--enable-disk-cache=static \
--enable-mem-cache=static \
--enable-socache-memcache=static \
--enable-cache-socache=static \
--enable-so=static \
--enable-dbd=static \
--enable-buffer=static \
--enable-reqtimeout=static \
--enable-include=static \
--enable-deflate=static \
--enable-http=static \
--enable-mime=static \
--enable-log-config=static \
--enable-log-debug=static \
--enable-log-forensic=static \
--enable-env=static \
--enable-mime-magic=static \
--enable-expires=static \
--enable-headers=static \
--disable-ident \
--enable-setenvif=static \
--enable-version=static \
--enable-remoteip=static \
--enable-session=static \
--enable-session-crypto=static \
--enable-socache-shmcb=static \
--enable-slotmem-shm=static \
--enable-request=static \
--enable-filter=static \
--enable-alias=static \
--enable-ssl=static \
-enable-ssl-staticlib-deps=static \
--with-openssldir=/usr/local/lib64 \
--with-ssl=/usr/local/lib64 \
--enable-unique-id \
--enable-http2=static \
--enable-geoip \
--enable-modules="reallyall" \
--enable-systemd \
--enable-proxy=static \
--enable-proxy-wstunnel=static \
--enable-proxy-http=static \
--enable-session-cookie=static \
--enable-session-dbd=static \
--enable-cgid=static \
--enable-unixd=static \
--enable-dav=static \
--enable-status=static \
--enable-autoindex=static \
--enable-info=static \
--enable-dave-fs=static \
--enable-vhost-alias=static \
--enable-negotiation=static \
--enable-dir=static \
--enable-speling=static \
--enable-userdir=static \
--with-module=aaa:/usr/src/mod_suphp/src/apache2/mod_suphp.c \
--enable-suexec-capabilities \
--with-module=aaa:/usr/src/mod-auth-external/mod_authnz_external/mod_authnz_external.c
