### ISSUE TITLE
mod_authz_unixgroup to support "and"

### ISSUE THREAD

**Issue by skimmy12** [phokz/mod-auth-external#46]
Currently mod_authz_unizgroup supports "or"
where:
Require unix-group staff admin
users in staff or admin are allowed.

Could you add a feature of "and"
where
Require unix-group staff
Require unix-group admin
only users in both staff and admin are allowed.

**Comment by bimimicah** [comment]
Now that I'm looking at this again, couldn't you just wrap it all in a `<RequireAll>`?
Like so:
```
<RequireAll>
    Require unix-group staff
    Require unix-group admin
</RequireAll>
```
For more info: [Apache access control tutorial](https://httpd.apache.org/docs/2.4/howto/access.html) and [`<RequireAll>` docs](https://httpd.apache.org/docs/2.4/mod/mod_authz_core.html#requireall)

If that doesn't work for some reason, feel free to reply here and we can try to figure out what's going on.
