### ISSUE TITLE
Each authentication request generates multiple invocations of mod_authnz_external

### ISSUE THREAD

**Issue by kmccurley** [phokz/mod-auth-external#51]
Our authentications are taking over four seconds, and I couldn't imagine why it is this slow. Our script invokes php to contact another server, and somehow this external php script is sending six different requests to the authentication server. This seems incomprehensible to us, since the script executes only a single HTTP request to the other server. Nevertheless, each invocation of mod_authnz_external translates into six different executions to the auth server, and apparently apache blocks until the last one finishes. This raises the question of what exactly is happening - is there any restart logic in the default configuration of mod_authnz_external that I was unable to find? I ran netstat -cant while it was executing an authentication, and sure enough it fires six different socket connections. The php code that does this is quite simple, and does just a POST to the server. This can timeout, but we don't have any retry logic in our php script.

$client = new \GuzzleHttp\Client();
$response = $client->request('POST', $auth_endpoint_url, ["form_params" => $query]);

Executing our script from the command line generates only a single POST, so this causes me to think that mod_authnz_external is invoking it multiple times for each authentication request from the apache server. 

We are using debian 11, apache 2.4.51-1~deb11u1, mpm_prefork, php 7.4.25, and this module built from master (looks like 3.3.3). We can try installing the debian package instead, but I'm grasping at straws to imagine how a single authentication request translates into six RPC calls.

**Comment by kmccurley** [comment]
Further information: it seems that apache is passing the http request to a single worker in mpm_prefork, and that worker is making multiple calls to exec_external, each of which spawns a separate process. The processes are completing correctly, but issuing six at once is causing it to be delayed considerably while it waits for all to finish. I looked at whether mod_authnz_external is killing them due to a timeout, but that's not the case (it uses APR_KILL_AFTER_TIMEOUT, which is 3 seconds by default in apache). I even set a sleep(5) in the external php authenticator, and it still wasn't killed.

This is quite baffling, since I cannot tell why apache would make multiple calls to the external authenticator for a single http request.

**Comment by bimimicah** [comment]
Sorry for the late response. Have you tried **setting apache's loglevel to debug** or higher and seeing **how many times per request mod_authnz_external is triggered**? If we know that, it should help narrow some things down.

_On a side note:_
One page load does not necessarily mean only one request for the page. In some situations (such as kerberos SSO (Negotiate)) it takes an initial auth failure and then the browser sends the proper authentication information on the second try.
Obviously that doesn't explain 6 different requests, It's just an example of how you might have multiple requests per page load even without requests for images, css, etc.

**Comment by bimimicah** [comment]
We never heard back from you, so hopefully you were able to diagnose the issue. Please reopen the issue and reply with your debug log results if you are still encountering the issue.

**Comment by kmccurley** [comment]
In the meantime I have come to the conclusion that authentication against the membership database seldom provides what I need to build applications for IACR. Examples include HotCRP, cryptodb, access to virtual conferences, administration of the cic.iacr.org and publish.iacr.org, administration of eprint, access to resources for the BOD, etc.

As an example, every time we set up a new HotCRP we have to manually create accounts for everyone, and then pull in the conflict of interest information and have the reviewer confirm it. HotCRP already has built-in support for LDAP, and now he is adding support for OAUTH2 via OpenID. In the meantime his major customer of ACM is moving toward using ORCID for OAUTH2. I don't see IACR requiring ORCID any time soon, but I also don't see any point for us to maintain an orthogonal approach to authentication. I have to set up 27 different HotCRP instances each year, and this may soon go to 36 per year for artifacts. It would be nice if we had a common authentication system (note that authors and reviewers are not always in the IACR database).

The `checkConfReg` endpoint turned out to not be that useful because conferences repeatedly screwed up their configuration for remote attendance and it was impossible to fix once it had been running for a while. I decided that access to virtual conferences for IACR did not require registration for the conference any more. The prevalence of workshops contributed to that problem. Program chairs were interfering with the planning of conferences because they didn't want remote presentations, but they seemed to be oblivious to the fact that there is always someone who misses a flight or gets sick or doesn't get a visa. In fact, the only thing I was trying to protect against in remote participation was abuse, and people had way too many problems with zoom that I didn't want to impose other failure modes through authentication. The `checkReadingRoom` and `checkPassword` endpoints didn't provide me with their name which was needed for the social app, and I decided it wasn't worth the trouble to implement another endpoint.

Incidentally, HotCRP doesn't run behind apache - we run it behind nginx because that is what is recommended. We don't seem to have an implementation of the basic authentication for nginx. For performance reasons we are probably moving toward nginx rather than apache in all future applications. Every app has its own notion of identity and authentication. As an example, the news distribution system doesn't require IACR membership. Neither does HotCRP or eprint. I recently brought up both janeway and OJS on our systems to test them for our publishing pipelines, and they only use standards-based authentication.

All of this has led me to believe that the authentication protocol doesn't really fit our needs. It works ok for access to the reading room and maintaining _paid_ attendance records at conferences, but that's about it. If we had a common framework like OAUTH2 then I could implement the usual "login with ORCID or google or IACR or apple or github or whatever" in our applications. Most of the applications don't store their authorization in the membership database. For example, the list of board members and list of reviewers and list of authors and list of remote attendees don't exist there.

As a result, I think it's ok to close this. None of the performance-sensitive applications are likely to use the API anyway. debugging apache doesn't seem relevant any more.

**Comment by bimimicah** [comment]
If you do find yourself back in the apache world someday, maybe [mod_oauth2](https://github.com/OpenIDC/mod_oauth2) is what you're looking for? (no endorsement, never used it)

As far as mod_authnz_external goes, it's primarily for filling niches that are not well served by other auth modules. For example, I personally use it to check already-issued login cookies against a custom backend to authorize downloading static files, which doesn't use the username/password part of mod_authnz_external at all, as the cookies are issued elsewhere.

Regardless, sounds like you've found something that works for you. That's good to hear. :)
