### ISSUE TITLE
mod-auth-external 3.3.3 has issue with external-group check

### ISSUE THREAD

**Issue by pbiering** [phokz/mod-auth-external#52]
something is weird since latest version on github

```
LoadModule authnz_external_module modules/mod_authnz_external.so

DefineExternalAuth pwauth pipe /usr/bin/pwauth
AuthExternal pwauth
AuthBasicProvider socache external
AuthExternalProvideCache On
AuthnCacheProvideFor external
Require user test
```
-> working fine

```
LoadModule authnz_external_module modules/mod_authnz_external.so

DefineExternalAuth pwauth pipe /usr/bin/pwauth
DefineExternalGroup unixgroup environment /usr/bin/unixgroup
AuthExternal pwauth
GroupExternal unixgroup
AuthBasicProvider socache external
AuthExternalProvideCache On
AuthnCacheProvideFor external
Require external-group monitor
```

returns after some requests

```
[Sun Jan 16 09:13:19.123176 2022] [authnz_external:error] [pid 2394628:tid 140390149625600] (10)No child processes: [client ***] Could not get status from child process, referer: https://SERVER/mrtg/index-month.html
[Sun Jan 16 09:13:19.163517 2022] [authnz_external:error] [pid 2394628:tid 140390149625600] [client ***] Authorization of user USER to access /mrtg/PICTURE.png failed. User not in Required group. Last result code: 1, referer: https://SERVER/mrtg/index-month.html
```
-> related to the external call of "unixgroup", which is a Perl program, have no idea what and why this is suddenly happend.

Changed now the configuration to use authz_unixgroup instead of calling external script "unixgroup":

```
LoadModule authnz_external_module modules/mod_authnz_external.so
LoadModule authz_unixgroup_module modules/mod_authz_unixgroup.so

DefineExternalAuth pwauth pipe /usr/bin/pwauth
AuthExternal pwauth
AuthBasicProvider socache external
AuthExternalProvideCache On
AuthnCacheProvideFor external
Require unix-group monitor
```

-> all works fine!

Has anyone the same issue seen?

**Comment by bimimicah** [comment]
Sorry for the late response. You said it worked previously? Which version worked before? And you're using latest master now, correct?
I haven't seen that error myself, but if you let me know which version worked, I can try to figure out what changed.
I'm glad we figured out the last issue you found. Hopefully we can fix this one too!

**Comment by bimimicah** [comment]
Also, where does /usr/bin/unixgroup come from? It doesn't seem to exist on CentOS 7, and I can't seem to find a man page for it anywhere. Maybe I'm not looking in the right place? [The only package with "unixgroup" in the name seems to be mod_authz_unixgroup](https://pkgs.org/search/?q=unixgroup).
mod_authz_unixgroup doesn't launch the unixgroup binary at all, it uses the system API directly.
Anyway, once you've determined where to find the documentation for /usr/bin/unixgroup, please check whether it expects environment variables or pipes, that could be a related issue.

**Comment by bimimicah** [comment]
Clearly I didn't read the original question very carefully, sorry. I see now that /usr/bin/unixgroup is your own Perl program, and your issue is that it is running flaky, not that it is not running at all. I'm not sure what I was thinking there.
I know it's been a long time, but please let us know if you've resolved it or if you're still having the issue.

**Comment by pbiering** [comment]
after changing to use of "mod_authz_unixgroup.so" all works fine.
