### ISSUE TITLE
Support PHP Sessions

### ISSUE THREAD

**Issue by carrvo** [phokz/mod-auth-external#58]
When mod-auth-external is directed (with `pipe` option) to a PHP script, it does not seem to include any previous session data. This is data from previous mod-auth-external calls or from PHP endpoints. For that matter, it does not seem to see `getenv` values that I set (in Apache) with `SetEnv`; nor does any `header('...')` seem to be passed back to the browser.

## Background
I already have a tidy little flow with a few PHP endpoints but since I don't know how to tell the browser "hey, use this token in your requests from now on" from the server, I came to `mod-auth-external` for a workaround. All I needed was a simple file (below) and I would be golden. Alas, PHP sessions seem to be empty during each run.
```php
<?php
start_session();
if (isset($_SESSION['token'])) {
    exit(0);
}
exit(1);
?>
```

**Comment by bimimicah** [comment]
External authenticators (such as your PHP script) **do not _modify_** the apache context (including environment variables) by design. They only return a success or failure code. Please see https://github.com/phokz/mod-auth-external/issues/42#issuecomment-686577277

As far as _receiving_ environment variables from Apache, only [the following list of environment variables](https://github.com/phokz/mod-auth-external/blob/a2751ee3717fe0713ae75c553a99efbd27ebcac5/mod_authnz_external/mod_authnz_external.c#L92) are passed to the external authenticator process.

If you want to pass something in an environment variable from Apache to the external process, you should set the "CONTEXT" environment variable.

**Comment by bimimicah** [comment]
Please also note the discussion of PHP sessions and session cookies [here](https://github.com/phokz/mod-auth-external/issues/42#issuecomment-686595150)

**Comment by carrvo** [comment]
> ...
>     Any existing cookies sent by the browser can be read. Creating cookies here is meaningless, since these are external and have nothing to do with Apache/BrowserRequest at all
> ...
> Please note: while you can read the value of an existing PHPSESSID cookie from an external script, the actual $_SESSION data will not be available from the external script unless PHP's global session.save_path variable and Apache's mod_php session.save_path variable point to the same location. This would depend on your server setup/environment.

~ https://github.com/phokz/mod-auth-external/issues/42#issuecomment-686577277

That describes *exactly* what I was trying to accomplish. Could this be documented somewhere instead of buried in a closed discussion that is not going to be found by someone now to the project?

I did not find
> the PHP script you are running via this module is external, meaning it is running in a separate process and is not in the current apache process at all. This means, for example, that PHP execution (via this module) is based solely on factors such as the global php.ini file, and is not at all affected by mod_php directives in apache's config files.

particularly intuitive to understand and would have led me to a solution much quicker without having to ask.

**Comment by bimimicah** [comment]
> ~ [#42 (comment)](https://github.com/phokz/mod-auth-external/issues/42#issuecomment-686577277)
> 
> That describes _exactly_ what I was trying to accomplish. Could this be documented somewhere instead of buried in a closed discussion that is not going to be found by someone now to the project?

My guess is the original authors (no longer with us; most of the wiki here is directly drawn from the old Google Code project) felt that "external authenticator" was self-explanatory 😆. From the readme:

> Mod_auth*_external allows the password checking normally done inside Apache to be done by an separate external program running outside of Apache.

When I joined the project, I felt it might need some clarification so I added the diagram below to the project readme:

> ![high-level overview diagram of mod_authnz_external](https://github.com/phokz/mod-auth-external/raw/master/documentation/mod_authnz_external%20overview.png)

### If you feel this is not enough, I'll see if I can write up some of these issue comments into a "What is an external authenticator?" page for the wiki with some explanation of the limitations.


.

**Comment by bimimicah** [comment]
> ~ [#42 (comment)](https://github.com/phokz/mod-auth-external/issues/42#issuecomment-686577277)
> 
> That describes _exactly_ what I was trying to accomplish. Could this be documented somewhere instead of buried in a closed discussion that is not going to be found by someone now to the project?

@carrvo, I added a new issue #59 for the writing new wiki page, feedback on that can go there.

**Comment by bimimicah** [comment]
The [new wiki page](https://github.com/phokz/mod-auth-external/wiki/ArchitectureConsiderations) has been added
